use crate::*;
use std::marker::PhantomData;

// -----------------------------------------------------------------------------
// Assignment starts here
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// Task 1: Nats.
// Implement the stream of natural numbers. Don't worry about overflow, still
// you can access the maximum usize with usize::MAX.
// -----------------------------------------------------------------------------
struct Nats {
    current: usize,
}

impl Stream<usize> for Nats {
    fn next(&mut self) -> Option<usize> {
        let val = self.current;
        self.current = self.current.saturating_add(1);
        Some(val)
    }
}

pub fn nats() -> impl Stream<usize> {
    Nats { current: 0 }
}

// -----------------------------------------------------------------------------
// Task 2: Take.
// Implement the stream that only consider the first n elements of a stream.
// Use it to implement the stream of the first three natural numbers.
// -----------------------------------------------------------------------------
struct Take<A, S: Stream<A>> {
    source: S,
    remaining: usize,
    _phantom: PhantomData<A>,
}

impl<A, S: Stream<A>> Stream<A> for Take<A, S> {
    fn next(&mut self) -> Option<A> {
        if self.remaining == 0 {
            return None;
        }
        self.remaining -= 1;
        self.source.next()
    }
}

pub fn take<A, S: Stream<A>>(source: S, n: usize) -> impl Stream<A> {
    Take {
        source,
        remaining: n,
        _phantom: PhantomData,
    }
}

pub fn one_two_three() -> impl Stream<usize> {
    take(nats(), 3)
}

// -----------------------------------------------------------------------------
// Task 3: Generation.
// Implement the stream whose elements are generated by repeatedly applying a
// function to the previous element, starting from an initial element. Use it to
// implement the stream of natural numbers.
// -----------------------------------------------------------------------------
struct Generate<A, F: Fn(&A) -> Option<A>> {
    current: Option<A>,
    generator: F,
}

impl<A, F: Fn(&A) -> Option<A>> Stream<A> for Generate<A, F> {
    fn next(&mut self) -> Option<A> {
        let current = self.current.take()?;
        self.current = (self.generator)(&current);
        Some(current)
    }
}

pub fn generate<A, F: Fn(&A) -> Option<A>>(init: A, generator: F) -> impl Stream<A> {
    Generate {
        current: Some(init),
        generator,
    }
}
pub fn generate_nats() -> impl Stream<usize> {
    generate(0_usize, |n| Some(n.saturating_add(1)))
}

// -----------------------------------------------------------------------------
// Task 4: Transformation.
// Implement the stream whose elements are generated taking elements from a
// stream and applying a function to each of them. Use it to implement the
// stream of squares.
// -----------------------------------------------------------------------------
struct Map<A, B, S: Stream<A>, F: Fn(&A) -> B> {
    source: S,
    mapfn: F,
    _phantom: PhantomData<(A, B)>,
}

impl<A, B, S: Stream<A>, F: Fn(&A) -> B> Stream<B> for Map<A, B, S, F> {
    fn next(&mut self) -> Option<B> {
        let value = self.source.next()?;
        Some((self.mapfn)(&value))
    }
}

pub fn map<A, B, S: Stream<A>, F: Fn(&A) -> B>(source: S, mapfn: F) -> impl Stream<B> {
    Map {
        source,
        mapfn,
        _phantom: PhantomData,
    }
}
pub fn squares() -> impl Stream<usize> {
    map(nats(), |n| n * n)
}

// -----------------------------------------------------------------------------
// Task 5: Filter.
// Implement the stream whose elements are generated by taking elements from a
// stream and discarding all those that do not satisfy a predicate. Use it to
// implement the stream of even natural numbers.
// -----------------------------------------------------------------------------
struct Filter<A, S: Stream<A>, F: Fn(&A) -> bool> {
    source: S,
    filterfn: F,
    _phantom: PhantomData<A>,
}

impl<A, S: Stream<A>, F: Fn(&A) -> bool> Stream<A> for Filter<A, S, F> {
    fn next(&mut self) -> Option<A> {
        loop {
            let value = self.source.next()?;
            if (self.filterfn)(&value) {
                return Some(value);
            }
        }
    }
}

pub fn filter<A, S: Stream<A>, F: Fn(&A) -> bool>(source: S, filterfn: F) -> impl Stream<A> {
    Filter {
        source,
        filterfn,
        _phantom: PhantomData,
    }
}
pub fn evens() -> impl Stream<usize> {
    filter(nats(), |n| n % 2 == 0)
}

// -----------------------------------------------------------------------------
// Task 6: Aggregate.
// Implement the stream whose elements are generated by updating an internal
// state by taking elements from a stream and applying a folding function to
// each of them. Use it to implement the stream of factorials.
// -----------------------------------------------------------------------------
struct Aggregate<A, B, S: Stream<A>, F: Fn(&B, &A) -> B> {
    source: S,
    state: Option<B>,
    fold: F,
    _phantom: PhantomData<A>,
}

impl<A, B, S: Stream<A>, F: Fn(&B, &A) -> B> Stream<B> for Aggregate<A, B, S, F> {
    fn next(&mut self) -> Option<B> {
        let current = self.state.take()?;
        if let Some(next_a) = self.source.next() {
            self.state = Some((self.fold)(&current, &next_a));
        }
        Some(current)
    }
}

pub fn aggregate<A, B, S: Stream<A>, F: Fn(&B, &A) -> B>(
    source: S,
    init: B,
    fold: F,
) -> impl Stream<B> {
    Aggregate {
        source,
        state: Some(init),
        fold,
        _phantom: PhantomData,
    }
}
pub fn factorials() -> impl Stream<usize> {
    aggregate(skip(nats(), 1), 1, |acc, n| acc * n)
}

// -----------------------------------------------------------------------------
// Task 7: Fluent Streams.
// Define a trait StreamOps that extends Stream with methods for all the
// previous operations, so that they can be chained in a fluent way. Provide an
// implementation of this trait for all Streams.
// -----------------------------------------------------------------------------

pub trait StreamOps<A>: Stream<A> {
    fn skip(self, n: usize) -> Self
    where
        Self: Sized,
    {
        skip(self, n)
    }
    fn take(self, n: usize) -> impl Stream<A>
    where
        Self: Sized,
    {
        take(self, n)
    }
    fn vec(self) -> Vec<A>
    where
        Self: Sized,
    {
        vec(self)
    }
    fn map<B, F: Fn(&A) -> B>(self, mapfn: F) -> impl Stream<B>
    where
        Self: Sized,
    {
        map(self, mapfn)
    }
    fn filter<F: Fn(&A) -> bool>(self, filterfn: F) -> impl Stream<A>
    where
        Self: Sized,
    {
        filter(self, filterfn)
    }
    fn aggregate<B, F: Fn(&B, &A) -> B>(self, init: B, fold: F) -> impl Stream<B>
    where
        Self: Sized,
    {
        aggregate(self, init, fold)
    }
}

impl<A, S: Stream<A>> StreamOps<A> for S {}

// -----------------------------------------------------------------------------
// Task 8: Streams from Vectors.
// Define a trait StreamableOnce that provides a method to consume any type to
// produce a corresponding Stream. Provide an implementation for Vec. Use it to
// define the stream of magic numbers [22, 13, 42].
// -----------------------------------------------------------------------------
pub trait StreamableOnce<A> {
    fn stream_once(self) -> impl Stream<A>;
}

struct VecOnceStream<A> {
    iter: std::vec::IntoIter<A>,
}

impl<A> Stream<A> for VecOnceStream<A> {
    fn next(&mut self) -> Option<A> {
        self.iter.next()
    }
}

impl<A> StreamableOnce<A> for Vec<A> {
    fn stream_once(self) -> impl Stream<A> {
        VecOnceStream {
            iter: self.into_iter(),
        }
    }
}

pub fn magic_numbers() -> impl Stream<usize> {
    vec![22_usize, 13, 42].stream_once()
}

// -----------------------------------------------------------------------------
// Task 9: Ownership.
// What is a limitation with StreamableOnce? Complete the code below by 
// providing an example that shows where it fails because of ownership, and 
// another that shows where it fails because of borrowing.
// -----------------------------------------------------------------------------
pub fn stream_once_ownership_failure() {
    //! ```compile_fail
    //! use project::*;
    //! // Useful application: stream the same vector twice to compute two
    //! // different aggregates over it (e.g., sum and product). Fails because
    //! // `stream_once` consumes `v` on the first call.
    //! let v: Vec<usize> = vec![1, 2, 3];
    //! let _sum_stream = v.stream_once();
    //! let _prod_stream = v.stream_once();
    //! ```
}
pub fn stream_once_borrowing_failure() {
    //! ```compile_fail
    //! use project::*;
    //! // Useful application: a function that streams a borrowed vector without
    //! // taking ownership, so the caller can keep using it. Fails because
    //! // `stream_once` requires moving the Vec out from behind the reference.
    //! fn collect_first_two(v: &Vec<usize>) -> Vec<usize> {
    //!     v.stream_once().take(2).vec()
    //! }
    //! ```
}

// -----------------------------------------------------------------------------
// Task 10: Lifetimes (Advanced).
// Define a trait Streamable that provides a method to convert any type into a
// a Stream without consuming it. Provide an implementation for Vec. Use it to
// solve the ownership and borrowing problems of Task 9.
// -----------------------------------------------------------------------------

pub trait Streamable<'a, A> {
    fn stream(&'a self) -> impl Stream<A> + 'a;
}

struct RefVecStream<'a, A> {
    iter: std::slice::Iter<'a, A>,
}

impl<'a, A> Stream<&'a A> for RefVecStream<'a, A> {
    fn next(&mut self) -> Option<&'a A> {
        self.iter.next()
    }
}

impl<'a, A: 'a> Streamable<'a, &'a A> for Vec<A> {
    fn stream(&'a self) -> impl Stream<&'a A> + 'a {
        RefVecStream { iter: self.iter() }
    }
}

pub fn stream_ownership_success() {
    //! ```
    //! use project::*;
    //! // The same useful application as in `stream_once_ownership_failure`,
    //! // now compiling: `stream` borrows the vec instead of consuming it,
    //! // so we can build multiple streams over the same vec.
    //! let v: Vec<usize> = vec![1, 2, 3];
    //! let _sum_stream  = v.stream();
    //! let _prod_stream = v.stream();
    //! ```
}
pub fn stream_borrowing_success() {
    //! ```
    //! use project::*;
    //! // The same function as in `stream_once_borrowing_failure`, now
    //! // compiling: `stream` accepts a borrowed `Vec`. Elements are streamed
    //! // by reference (`&usize`), avoiding any clone.
    //! fn collect_first_two(v: &Vec<usize>) -> Vec<&usize> {
    //!     v.stream().take(2).vec()
    //! }
    //! ```
}
